[[redirects]]
  from = "/api/*"
  to = "https://next-project-server.herokuapp.com/:splat"
  status = 200
  force = true

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "https://next-project-server.herokuapp.com/"